name: MySQL Server and API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci --no-package-lock

      - name: Start MySQL container
        run: |
          docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=1998@Pupss -e MYSQL_DATABASE=assignment1 -d -p 3306:3306 mysql:latest
          sleep 10
          docker ps -a
          docker logs mysql-container
        continue-on-error: true

      - name: Check MySQL health
        run: docker exec mysql-container mysqladmin ping -h localhost -P 3306 -u root -p1998@Pupss

      
      - name: Run tests
        run: npm test
  
      - name: Start app
        run: npm start &
  
      - name: Test /healthz
        run: |
          if [ $(curl -s http://localhost:9000/healthz) = "200" ]; then
            echo "Health check passed"
          else
            echo "Health check failed"  
            exit 1
          fi
