name: Node.js CI

on:
  push:
    branches: [main] 
  pull_request:
    branches: [main]

jobs:

  test:

    runs-on: ubuntu-latest
    
    services:
      db:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
    
    - name: Install dependencies  
      run: npm ci
      
    - name: Create DB
      run: |
        mysql -h 127.0.0.1 -u root -p password -e "CREATE DATABASE mydb"
    
    - name: Run tests
      run: npm test
            
    - name: Start app
      run: npm start &
    
    - name: Check /healthz endpoint
      run: |  
        if [[ $(curl -s http://localhost:9000/healthz) == "200" ]]; then
          echo "Success"
        else
          echo "Failed healthcheck"
          exit 1
        fi
