name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]



jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1998@Pupss
          MYSQL_DATABASE: assignment1
        ports:
            - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
          
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2

    - name: Install dependencies
      run: npm install

    # Use systemctl to control service
    - name: Start MySQL
      run: sudo systemctl start mysql

    - name: Verify MySQL status
      run: sudo systemctl status mysql

    - name: Check MySQL logs
      run: sudo journalctl -u MySQL 


    - name: Grant CREATE privilege to root user
      run: mysql -u root -p"1998@Pupss" -e "GRANT CREATE ON *.* TO 'root'@'localhost' WITH GRANT OPTION;"


    - name: Create DB
      run: |
          if ! mysql -u root -p1998@Pupss -e "CREATE DATABASE assignment1"; then
          echo "Failed to create the database"
          exit 1
          fi

    - name: Check MySQL Error Log
      run: sudo cat /var/log/mysql/error.log

    - name: Run tests
      run: npm test

    - name: Start app
      run: npm start &

    - name: Test /healthz
      run: |
        if [ $(curl -s http://localhost:9000/healthz) = "200" ]; then
          echo "Health check passed"
        else
          echo "Health check failed"  
          exit 1
        fi
