name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MYSQL_ROOT_PASSWORD: "1998@Pupss"

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      db:
        image: mysql 
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2

    - name: Install dependencies
      run: npm install

    # Use systemctl to control service
    - name: Start MySQL
      run: sudo systemctl start mysql

    - name: Verify MySQL status
      run: sudo systemctl status mysql

    - name: Check MySQL logs
      run: sudo journalctl -u mysql 

    - name: Create DB
      run: |
        mysql -u root -p ${{ env.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE assignment1"

    - name: Run tests
      run: npm test

    - name: Start app
      run: npm start &
        
    - name: Test /healthz
      run: |
        if [ $(curl -s http://localhost:9000/healthz) = "200" ]; then
          echo "Health check passed"
        else
          echo "Health check failed"  
          exit 1
        fi
