name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 1998@Pupss
          MYSQL_DATABASE: assignment1
        ports:
          - 3306:3306

    defaults:
      run:
        working-directory: server.js

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './server/package-lock.json'
    - run: npm install
    - run: npm run build --if-present
    - name: Start Node.js Server
      run: npm start &
    - name: Wait for Node.js Server to Start
      run: sleep 10 # Adjust as needed
    - name: Test /healthz
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9000/healthz)
        if [ "$response" = "200" ]; then
          echo "Health check passed"
        else
          echo "Health check failed"
          exit 1
        fi
