name: MySQL Server and API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server

      - name: Start MySQL service
        run: sudo service mysql start

      - name: Configure MySQL
        run: |
          echo "[mysqld]" | sudo tee -a /etc/mysql/mysql.conf.d/mysqld.cnf
          echo "skip-log-bin" | sudo tee -a /etc/mysql/mysql.conf.d/mysqld.cnf
          sudo service mysql restart
          mysql -e "CREATE DATABASE assignment1;"
        continue-on-error: true

      - name: Set MySQL root password
        run: |
          mysqladmin -u root password '1998@Pupss'

      - name: Install dependencies
        run: npm ci --no-package-lock

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h localhost -u root -p1998@Pupss; then
              break
            else
              echo "MySQL not ready, retrying in 5 seconds..."
              sleep 5
            fi
          done
  
      - name: Start app
        run: npm start &

      - name: Test /healthz
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9000/healthz)
          if [ -n "$response" ] && [ "$response" = "200" ]; then
            echo "Health check passed"
          else
            echo "Health check failed"  
            exit 1
          fi
